import type { Metadata } from "next";

import DashboardLayout from "./components/DashboardLayout.js";
import "./globals.css";




// Métadonnées globales
export const metadata: Metadata = {
  title: "Hesproject",
  description: "Generated by create next app",
};

// Root Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DashboardLayout>{children}</DashboardLayout>
      </body>
    </html>
  );
}
